services:
  bitmind_validator:
    build: 
      context: .
    container_name: bitmind_validator
    restart: unless-stopped
    entrypoint: ./entrypoint.sh
    ports:
      - '${VALIDATOR_AXON_PORT}:${VALIDATOR_AXON_PORT}'
    volumes:
      - ./container-data/.bittensor:/root/.bittensor
      - ./container-data/.cache/huggingface:/root/.cache/huggingface
    env_file:
      - .env
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]